### ISSUE TITLE
KeyError: 'names'

### ISSUE THREAD

**Issue by jeffencillo** [mdenolle/NoisePy#30]
Hello, I'm getting this error when I run **S0B_to_ASDF.py**;
  
_File "S0B_to_ASDF.py", line 104, in <module>
    all_stimes = noise_module.make_timestamps(prepro_para)
  File "/Users/mac/NoisePy/src/noise_module.py", line 95, in make_timestamps
    allfiles = tmp['names']
  File "/Users/mac/anaconda3/envs/noisepy/lib/python3.7/site-packages/pandas/core/frame.py", line 2902, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/mac/anaconda3/envs/noisepy/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'names'_

Please let me know on how to resolve this.  Thanks in advance.

**Comment by chengxinjiang** [comment]
@jeffencillo apologize for the late reply. The issue you have is due to a miss of a "names" column in your allfiles_time.txt file. Below shows an example of the allfiles_time.txt file. Let me know if this makes sense. 

names,starttime,endtime
/Users/chengxin/Documents/NoisePy_example/LP/sac_data/20190816000344324.5.EHN.LP.sac,1565913824.324,1566000224.325273
/Users/chengxin/Documents/NoisePy_example/LP/sac_data/20190816001908480.1.EHE.LP.sac,1565914748.48,1566001148.481273
